---
- hosts: all_in_one
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - postgres
    - redis
    - django-application
    - django-static
    - django-runserver
    - genesis-health-reading-server
    - celery
    - nginx
- hosts: web
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - django-application
    - django-static
    - django-gunicorn
    - nginx
- hosts: worker
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - django-application
    - celery
- hosts: reading
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - django-application
    - genesis-health-reading-server