---
- hosts: all_in_one
  become: yes
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - postgres
    - redis
    - django-application
    - django-static
    - django-runserver
    - genesis-health-reading-server
    - celery
    - celery-beat
    - genesis-health-encrypt
    - nginx
- hosts: web
  become: yes
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - django-application
    - django-static
    - django-gunicorn
    - genesis-health-encrypt
    - nginx
- hosts: worker-leader
  become: yes
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - django-application
    - genesis-health-encrypt
    - celery
    - celery-beat
- hosts: worker
  become: yes
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - django-application
    - genesis-health-encrypt
    - celery
- hosts: reading
  become: yes
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - django-application
    - genesis-health-encrypt
    - genesis-health-reading-server
- hosts: development
  become: yes
  roles:
    - common-vars
    - genesis-health-common
    - secrets
    - configure-server
    - supervisor
    - redis
    - django-application
    - django-static
    - django-runserver
    - genesis-health-reading-server
    - celery
    - celery-beat
    - genesis-health-encrypt
    - nginx