---
- name: Enable python binary to access port 443
  become: true
  capabilities:
    path: /usr/bin/python3.6
    capability: cap_net_bind_service+eip
    state: present
- include_role:
    name: supervisor
    tasks_from: add-conf
  vars:
    item:
      process_name: reading_spy
      command: "{{ virtualenv_dir }}/bin/python {{ virtualenv_dir }}/bin/manage.py reading_spy"